apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbadges-explorer
  labels:
    app: bitbadges-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitbadges-explorer
  template:
    metadata:
      labels:
        app: bitbadges-explorer
    spec:
      containers:
        - name: bitbadges-explorer
          image: trevormil23/bitbadges-explorer:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: bitbadges-explorer-config
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
